image: gitpod/workspace-node-lts
# Learn more from ready-to-use templates: https://www.gitpod.io/docs/introduction/getting-started/quickstart
ports:
  - port: 3000
    onOpen: open-preview

tasks:
  - init: npm install
      npm install nodemon
    command: nodemon index.js
